language: python
virtualenv:
  system_site_packages: true
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: tox
env:
  - TOXENV=py27sqlite
  - TOXENV=py27pg
  - TOXENV=flake8
  - TOXENV=packaging
after_success:
  - coveralls
notifications:
  email:
  - rajat.gupta712@gmail.com